add_subdirectory(fix)
add_subdirectory(flatbuffers)
add_subdirectory(protobuf)
add_subdirectory(sbe)

set(TARGET_NAME ${PROJECT_NAME})

set(TARGET_DIR ${SCHEMA_DIR})

set(SOURCES
    Action.json
    AddMarket.json
    AddRoutes.json
    Bar.json
    BatchBegin.json
    BatchEnd.json
    BufferCapacity.json
    CancelAllOrders.json
    CancelAllOrdersAck.json
    CancelOrder.json
    CancelQuotes.json
    CancelQuotesAck.json
    Category.json
    Connected.json
    ConnectionStatus.json
    Control.json
    ControlAck.json
    CreateOrder.json
    CustomMatrix.json
    CustomMatrixUpdate.json
    CustomMetrics.json
    CustomMetricsUpdate.json
    DataSource.json
    Disconnected.json
    DownloadBegin.json
    DownloadEnd.json
    Encoding.json
    Error.json
    ExchangeSymbol.json
    ExecutionInstruction.json
    ExternalLatency.json
    Fill.json
    Filter.json
    FundsUpdate.json
    GatewaySettings.json
    GatewayStatus.json
    Handshake.json
    HandshakeAck.json
    Interval.json
    Layer.json
    Leg.json
    LegsUpdate.json
    Liquidity.json
    MBOUpdate.json
    MBPUpdate.json
    MarginMode.json
    MarketByOrderUpdate.json
    MarketByPriceUpdate.json
    MarketStatus.json
    MassQuote.json
    MassQuoteAck.json
    Measurement.json
    MessageInfo.json
    ModifyOrder.json
    OptionType.json
    OrderAck.json
    OrderCancelPolicy.json
    OrderManagement.json
    OrderStatus.json
    OrderType.json
    OrderUpdate.json
    Origin.json
    Parameter.json
    ParametersUpdate.json
    Portfolio.json
    PortfolioUpdate.json
    PositionEffect.json
    Position.json
    PositionUpdate.json
    Precision.json
    Priority.json
    Protocol.json
    QualityOfService.json
    QuantityType.json
    Quote.json
    RateLimit.json
    RateLimitsUpdate.json
    RateLimitTrigger.json
    RateLimitType.json
    Ready.json
    ReferenceData.json
    RemoveRoutes.json
    RequestIdType.json
    RequestStatus.json
    RequestType.json
    RiskLimit.json
    RiskLimits.json
    RiskLimitsUpdate.json
    RouteAck.json
    Route.json
    RouteRequestStatus.json
    Routing.json
    SecurityType.json
    ServiceUpdate.json
    Side.json
    Start.json
    State.json
    Statistics.json
    StatisticsType.json
    StatisticsUpdate.json
    Stop.json
    StrategyUpdate.json
    StreamStatus.json
    Subscribe.json
    SupportType.json
    TickSizeStep.json
    TimeInForce.json
    Timer.json
    TimeSeriesUpdate.json
    TopOfBook.json
    Trade.json
    TradeSummary.json
    TradeUpdate.json
    TradingStatus.json
    Transport.json
    UpdateAction.json
    UpdateReason.json
    UpdateType.json
    VariantType.json)

install(FILES ${SOURCES} DESTINATION ${TARGET_DIR})
