message CreateOrder {
  string account = 1;
  uint64 order_id = 2;
  string exchange = 3;
  string symbol = 4;
  Side side = 5;
  optional PositionEffect position_effect = 6;
  optional MarginMode margin_mode = 7;
  optional QuantityType quantity_type = 8;
  optional double max_show_quantity = 9;
  OrderType order_type = 10;
  optional TimeInForce time_in_force = 11;
  repeated ExecutionInstruction execution_instructions = 12;
  string execution_destination = 13;
  optional string request_template = 14;
  optional double quantity = 15;
  optional double price = 16;
  optional double stop_price = 17;
  optional double leverage = 18;
  optional string routing_id = 19;
  optional uint32 strategy_id = 20;
  optional google.protobuf.Timestamp release_time_utc = 21;
}
