message OrderUpdate {
  uint32 stream_id = 1;  // uint16
  string account = 2;
  uint64 order_id = 3;
  string exchange = 4;
  string symbol = 5;
  Side side = 6;
  optional PositionEffect position_effect = 7;
  optional MarginMode margin_mode = 8;
  optional QuantityType quantity_type = 9;
  optional double max_show_quantity = 10;
  OrderType order_type = 11;
  optional TimeInForce time_in_force = 12;
  repeated ExecutionInstruction execution_instructions = 13;
  string execution_destination = 14;
  optional google.protobuf.Timestamp create_time_utc = 15;
  optional google.protobuf.Timestamp update_time_utc = 16;
  optional string external_account = 17;
  optional string external_order_id = 18;
  string client_order_id = 19;
  OrderStatus order_status = 20;
  optional double quantity = 21;
  optional double price = 22;
  optional double stop_price = 23;
  optional double leverage = 24;
  optional double risk_exposure = 25;
  optional double risk_exposure_change = 26;
  optional double remaining_quantity = 27;
  optional double traded_quantity = 28;
  optional double average_traded_price = 29;
  optional double last_traded_quantity = 30;
  optional double last_traded_price = 31;
  optional Liquidity last_liquidity = 32;
  optional string routing_id = 33;
  uint32 max_request_version = 34;
  uint32 max_response_version = 35;
  uint32 max_accepted_version = 36;
  UpdateType update_type = 37;
  optional google.protobuf.Timestamp exchange_time_utc = 38;
  optional uint64 exchange_sequence = 39;
  optional google.protobuf.Timestamp sending_time_utc = 40;
  string user = 41;
  optional uint32 strategy_id = 42;
}
