message OrderAck {
  uint32 stream_id = 1;  // uint16
  string account = 2;
  uint64 order_id = 3;
  string exchange = 4;
  string symbol = 5;
  Side side = 6;
  optional PositionEffect position_effect = 7;
  optional MarginMode margin_mode = 8;
  optional QuantityType quantity_type = 9;
  RequestType request_type = 10;
  Origin origin = 11;
  RequestStatus request_status = 12;
  optional Error error = 13;
  optional string text = 14;
  string request_id = 15;
  optional string external_account = 16;
  optional string external_order_id = 17;
  string client_order_id = 18;
  optional double quantity = 19;
  optional double price = 20;
  optional double stop_price = 21;
  optional double leverage = 22;
  optional string routing_id = 23;
  uint32 version = 24;
  optional double risk_exposure = 25;
  optional double risk_exposure_change = 26;
  optional double traded_quantity = 27;
  optional google.protobuf.Timestamp round_trip_latency = 28;
  string user = 29;
  optional uint32 strategy_id = 30;
}
