message TradeUpdate {
  uint32 stream_id = 1;  // uint16
  string account = 2;
  uint64 order_id = 3;
  string exchange = 4;
  string symbol = 5;
  Side side = 6;
  optional PositionEffect position_effect = 7;
  optional MarginMode margin_mode = 8;
  optional QuantityType quantity_type = 9;
  optional google.protobuf.Timestamp create_time_utc = 10;
  optional google.protobuf.Timestamp update_time_utc = 11;
  optional string external_account = 12;
  string external_order_id = 13;
  string client_order_id = 14;
  repeated Fill fills = 15;
  optional string routing_id = 16;
  UpdateType update_type = 17;
  optional google.protobuf.Timestamp exchange_time_utc = 18;
  optional uint64 exchange_sequence = 19;
  optional google.protobuf.Timestamp sending_time_utc = 20;
  string user = 21;
  optional uint32 strategy_id = 22;
}
