message ReferenceData {
  uint32 stream_id = 1;  // uint16
  string exchange = 2;
  string symbol = 3;
  optional string description = 4;
  optional SecurityType security_type = 5;
  optional int32 external_security_id = 6;
  optional string cfi_code = 7;
  optional string base_currency = 8;
  optional string quote_currency = 9;
  optional string settlement_currency = 10;
  optional string margin_currency = 11;
  optional string commission_currency = 12;
  optional double tick_size = 13;
  repeated TickSizeStep tick_size_steps = 14;
  optional double multiplier = 15;
  optional double min_notional = 16;
  optional double min_trade_vol = 17;
  optional double max_trade_vol = 18;
  optional double trade_vol_step_size = 19;
  optional OptionType option_type = 20;
  optional string strike_currency = 21;
  optional double strike_price = 22;
  optional string underlying = 23;
  optional string time_zone = 24;
  optional google.protobuf.Timestamp issue_date = 25;
  optional google.protobuf.Timestamp settlement_date = 26;
  optional google.protobuf.Timestamp expiry_datetime = 27;
  optional google.protobuf.Timestamp expiry_datetime_utc = 28;
  optional google.protobuf.Timestamp exchange_time_utc = 29;
  optional uint64 exchange_sequence = 30;
  optional google.protobuf.Timestamp sending_time_utc = 31;
  bool discard = 32;
}
